### ISSUE TITLE
After recent update, GraXpert script won't run

### ISSUE THREAD

**Issue by deathtical** [Steffenhir/GraXpert#124]
Installed a new update for PI this morning and now GraXpert won't run.

Processing script file: C:/Program Files/PixInsight/src/scripts/Toolbox/Graxpert.js
*** Error: Signature verification failed for 'GraXpert': Invalid code signature: C:/Program Files/PixInsight/src/scripts/Toolbox/Graxpert.js

Some other scripts in the Toolbox seem to be working. Any ideas?

EDIT: I have also installed the latest update for GraXpert.

**Comment by schmelly** [comment]
Hi @deathtical,

the latest PixInsight release 1.8.9-2 / Build 1597 apparently raised issues wrt. code signing of some scripts in the PI Toolbox. Jürgen published a new Toolbox release just yesterday (i.e., on 2024-01-22) which should solve these issues. Please make sure to update the Toolbox Scripts again / once more.

If you need further support I suggest you join our Discord since GraXpert Script is not part of this repository:
https://discord.gg/bVgeWXas

Best regards and CS
David

**Comment by deathtical** [comment]
According to updates, it says all my repositories are up to date. When I'm done with my current image, I will remove and re-install the Toolbox set.

**Comment by deathtical** [comment]
Ok. I did a "reset updates" restarted PI, PI installed all updates from the repositories but still get the same error from GraXpert. All other scripts in the Toolbox work without error. Any other ideas?

Thanks

**Comment by JuergenTerpe** [comment]
Hi @deathtical,

Reset updates must work, for unknown reason two scripts did not get a correct code signing, but the updated package included correct code signing and it works as expected. I regret if you still having trouble! The fastest and easiest solution would be to just remove the file Graxpert.xsgn. You can find it inside the PixInsight application folder under: 

PixInsight/src/scripts/Toolbox/Graxpert.xsgn

This also requires that you enable "Allow execution of unsigned scripts" in Global Preferences under Security.  

If you are not comfortable with this you must again reset updates and drop the entire Toolbox folder before updating all repositories to ensure you will get all files copied into this folder (maybe PixInsight could not replace the files for some reason). 

Sorry for this inconvenience, Jürgen!

**Comment by deathtical** [comment]
@JuergenTerpe 

OK. I didn't delete the Graxpert.xsgn filke but renamed it to Graxpert.xsgn.old. Now I am able to run the GraXpert tool without error. I already had the "Allow execution of unsigned scripts" enabled.

Thanks
